# 此工作流检出代码并扫描上次提交中更改或添加的内容，
# 查找冒犯性/排他性术语。
# 扫描将提供关于发现的术语和可以使用的替代术语的上下文。

name: 包容性分析扫描

on:
  push:
    branches: [main]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  Inclusiveness-Analyser-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 加固运行器（审计所有出站调用）
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: 检出代码
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: 包容性分析器
        uses: microsoft/InclusivenessAnalyzer@994519a4cd1f0ccc7415fff13b7f287344c420bc # v1.0.1